FROM ubuntu:20.04

RUN apt-get update		\
    && apt-get install -y	\
    nginx			\
    sqlite3			\
    php-fpm			\
    php-mysql			\
    php-intl			\
    php-mbstring		\
    php-zip			\
    php-xml			\
    php-sqlite3

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/php.ini /etc/php/7.4/fpm/php.ini
COPY docker/default /etc/nginx/sites-available/default

WORKDIR /var/www/html

CMD service php7.4-fpm start 	\
    && nginx -g 'daemon off;'	\
    && bash
